services:
  php:
    build: ./php
    container_name: php
    command: php -S 0.0.0.0:${MOODLE_PORT} -t /var/www/html/moodle/
    ports:
      - "${MOODLE_PORT}:${MOODLE_PORT}"
    environment:
      PHP_IDE_CONFIG: "serverName=${PHPSTORM_SERVER_NAME}"
    restart: always
    volumes:
      - ./moodle:/var/www/html/moodle/
      - ./moodledata:/var/www/html/moodledata/
      - ./php/configs:/usr/local/etc/php
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"


  database:
    image: mysql:8.4
    container_name: database
    restart: always
    ports:
      - "${MYSQL_8_4_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql