services:
  php-8.3:
    build: ./php-8.3
    container_name: php-8.3
    command: php -S 0.0.0.0:${MOODLE_PORT} -t /var/www/html/moodle/
    ports:
      - "${MOODLE_PORT}:${MOODLE_PORT}"
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    restart: always
    volumes:
      - ./moodle:/var/www/html/moodle/
      - ./moodledata:/var/www/html/moodledata/
      - ./php-8.3/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql-8.4
    profiles:
      - moodle-4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql-5.7:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    ports:
      - "${MYSQL_5_7_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-5.7/data:/var/lib/mysql
    profiles:
      - moodle-3.8

  mysql-8.4:
    image: mysql:8.4
    container_name: mysql-8.4
    restart: always
    ports:
      - "${MYSQL_8_4_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-8.4/data:/var/lib/mysql
    profiles:
      - moodle-4.4
